name = "Cobblemon"
author = "Douglas Parker"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2692595efffcfdbc6b42c8fb298d9997915d19516775ed16e10ac44a2c6af5cc"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
